import { RevealCard } from '@/components/motion';
import { useId } from 'react';
import { AreaChart, Area, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { CalendarCheck, Wallet } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from './ui/card';
import { formatCurrency } from '@/lib/format';

interface Props {
  attendance: { present:number; absent:number; late:number; leave:number; total:number };
  monthly: { month:string; collection:number; income:number; expenses:number }[];
}
export function DashboardAnalytics({ attendance, monthly }: Props) {
 const id=useId().replace(/:/g,'');
 const statuses=[{label:'Present',value:attendance.present,color:'var(--brand-primary)'},{label:'Absent',value:attendance.absent,color:'#cb736c'},{label:'Late',value:attendance.late,color:'#c5a45e'},{label:'Leave',value:attendance.leave,color:'#83b9a8'}];
 const total=statuses.reduce((sum,s)=>sum+s.value,0);
 const present=total?Math.round(attendance.present/total*100):0;
 let offset=0;
 const stops=statuses.map(s=>{const start=offset;offset+=total?s.value/total*100:0;return `${s.color} ${start}% ${offset}%`;}).join(',');
 return <div className="grid min-w-0 gap-5 xl:grid-cols-[.85fr_1.4fr]">
 <RevealCard><CardHeader><CardTitle className="flex items-center gap-2"><CalendarCheck className="h-4 w-4 text-primary"/>Attendance overview</CardTitle><CardDescription>Today’s marked student attendance</CardDescription></CardHeader><CardContent><div className="flex flex-wrap items-center justify-center gap-8 py-3"><div role="img" aria-label={total?`${present}% present. ${statuses.map(s=>`${s.value} ${s.label.toLowerCase()}`).join(', ')}`:'No attendance marked today'} className="grid h-36 w-36 shrink-0 place-items-center rounded-full" style={{background:total?`conic-gradient(${stops})`:'hsl(var(--muted))'}}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-card"><strong className="text-3xl font-semibold tracking-tight">{total?`${present}%`:'—'}</strong><span className="mt-1 text-xs text-muted-foreground">{total?'Present':'Not marked'}</span></div></div><div className="min-w-28 space-y-3">{statuses.map(s=><div key={s.label} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full" style={{background:s.color}}/><span className="flex-1 text-muted-foreground">{s.label}</span><strong className="font-medium tabular-nums">{s.value}</strong></div>)}</div></div>{!total&&<p className="mt-3 text-center text-xs text-muted-foreground">Mark attendance to see today’s overview.</p>}</CardContent></RevealCard>
 <RevealCard className="min-w-0"><CardHeader><CardTitle className="flex items-center gap-2"><Wallet className="h-4 w-4 text-primary"/>Fee collection</CardTitle><CardDescription>Recorded collections by month</CardDescription></CardHeader><CardContent>{monthly.some(m=>m.collection>0)?<><div className="h-52 w-full" role="img" aria-label="Monthly fee collection chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly} margin={{left:0,right:10,top:12,bottom:0}}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--brand-primary)" stopOpacity={.22}/><stop offset="100%" stopColor="var(--brand-primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="hsl(var(--border))" vertical={false} strokeDasharray="4 4"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'hsl(var(--muted-foreground))'}}/><YAxis width={48} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'hsl(var(--muted-foreground))'}} tickFormatter={v=>v>=100000?`${v/100000}k`:String(v/100)}/><Tooltip formatter={(v:number)=>formatCurrency(v)} contentStyle={{borderRadius:14,background:'hsl(var(--card))',border:'1px solid hsl(var(--border))',color:'hsl(var(--foreground))'}}/><Area name="Collection" type="monotone" dataKey="collection" stroke="var(--brand-primary)" strokeWidth={2.5} fill={`url(#${id})`} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><details className="mt-3 text-xs text-muted-foreground"><summary className="cursor-pointer">View collection figures</summary><ul className="mt-3 space-y-2">{monthly.map(m=><li key={m.month} className="flex justify-between"><span>{m.month}</span><span>{formatCurrency(m.collection)}</span></li>)}</ul></details></>:<div className="flex h-52 flex-col items-center justify-center rounded-2xl bg-muted/50 text-center"><Wallet className="mb-3 h-7 w-7 text-primary"/><p className="font-medium">Your collection story starts here</p><p className="mt-2 max-w-xs text-xs text-muted-foreground">Recorded fee payments will appear in your monthly collection chart.</p></div>}</CardContent></RevealCard></div>;
}
